### ISSUE TITLE
Limited data when trying to call matic.get_normal_txs_by_address

### ISSUE THREAD

**Issue by tungrix** [tarsil/polygonscan-python#5]
Is it possible to get more than 10000 numbers of data, when trying to call matic.get_normal_txs_by_address or using polygonscan original APIs? 

I want to get all the historical transaction records of the address.

Please help, thanks.

**Comment by pepi99** [comment]
I think no.

**Comment by tarsil** [comment]
It's impossible, the package is only limited to the what the API can also do. I understand why you would like that because that would save you a lot of calls but as you know, polygonscan also limits the total number. 

Apologies for taking so long to reply but I have never received a notification from GitHub saying this was here.
